PUT http://localhost:5000/api/chats/65d3fb9ceb99bd032d32793e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWNlYTFjNzYwYTM4ODQ2YjE4ODRhM2EiLCJlbWFpbCI6Im1hbGJvcm9kbzEyM0BnbWFpbC5jb20iLCJpYXQiOjE3MTI5NTYzMTcsImV4cCI6MTcxMjk1OTkxN30.k6PH1eNFxNI-tInSAySECez69Y2U008RE1X-hmUoSj4
Content-Type: application/json

{
  "userId": "66159624d89f60d1b6ca22d5"
}
